# Generated by Django 5.2.8 on 2025-12-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="All_Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=225, unique=True)),
                ("phone_no", models.CharField(max_length=10, unique=True)),
                ("class_assigned", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=255)),
                ("joining_date", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=30)),
            ],
        ),
    ]
