# Generated by Django 5.2.8 on 2025-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=20)),
                ("class_teacher", models.CharField(max_length=255)),
                ("class_teacher_id", models.CharField(max_length=10)),
                ("strength", models.IntegerField()),
                ("academic_year", models.CharField(max_length=20)),
            ],
        ),
    ]
