# Generated by Django 5.2.8 on 2025-12-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_classes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassTeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("is_class_teacher", models.BooleanField(default=False)),
                ("academic_year", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("ongoing", "Ongoing"), ("completed", "Completed")],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.classes",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.all_teacher",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("teacher", "class_obj", "subject", "academic_year")
                },
            },
        ),
    ]
