# Generated by Django 5.2.8 on 2025-12-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_classteacherassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="classteacherassignment",
            name="teacher_name",
            field=models.CharField(default="unknown", max_length=255),
            preserve_default=False,
        ),
    ]
