# Generated by Django 5.2.8 on 2025-12-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_classteacherassignment_teacher_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "Ongoing"), ("completed", "Completed")],
                default="ongoing",
                max_length=20,
            ),
        ),
    ]
