# Generated by Django 5.2.8 on 2025-12-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_classes_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classteacherassignment",
            name="status",
        ),
    ]
