# Generated by Django 5.2.8 on 2025-12-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_remove_classteacherassignment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "admission_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("roll_no", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("father_name", models.CharField(max_length=255)),
                ("mother_name", models.CharField(max_length=255)),
                ("phone_no", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.classes",
                    ),
                ),
            ],
        ),
    ]
