# Generated by Django 5.2.8 on 2025-11-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="USER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=225, unique=True)),
                ("Role", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=200)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
