# Generated by Django 5.2.8 on 2025-12-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_system", "0002_announcement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
